app = 'migos'
primary_region = 'iad'

[build]
  builder = "heroku/buildpacks:20"
  buildpacks = ["gcr.io/paketo-buildpacks/nodejs"]

[build.args]
  NODE_VERSION = "20.18.0"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'