app = "migos"
primary_region = "bos"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/nodejs"]
  ignorefile = "./docker-compose.yaml"

[deploy]
  release_command = "pnpm install && pnpm run build"
  strategy = "bluegreen"
  max_unavailable = 1
  internal_port = 8080
  force_https = true

[processes]
  app = "pnpm run start"

[http_service]
  processes = ["app"]
  internal_port = 8080
  force_https = true